binary-buildpack/binary-buildpack-cflinuxfs2-v1.0.27.zip:
  size: 3624496
  object_id: 0f14e953-bb36-4f80-4d7c-5d51a0069ee2
  sha: 8ed1bf1ab006788fdfbca9ddb59e48c3213c048b
binary-buildpack/binary-buildpack-cflinuxfs3-v1.0.27.zip:
  size: 3624498
  object_id: 4974a982-df66-4037-4fbf-0f6728e38c0b
  sha: 67800b792598e442a03f064bb42a3cc3677af704
binary-buildpack/binary-buildpack-windows2012R2-v1.0.27.zip:
  size: 3624500
  object_id: f5610ba7-327f-4a55-7686-6a372496f826
  sha: 7d0530290fb3416068c046c4762464f0106ebee1
binary-buildpack/binary-buildpack-windows2016-v1.0.27.zip:
  size: 3624500
  object_id: e4157830-694e-42c4-743c-5519234d8527
  sha: 9052962a99bb456eb722bf30593f202812aeda7a
